name: BrandonBridges
favicon: null
layout_spectrum: 0.7592
typography_spectrum: 0.43386
title: "Hard work beats talent when talent doesn't work hard"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a0100'
    - '#30384b'
    - '#d2bb9b'
    - '#909cb6'
    - '#784d3d'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
