name: BrandonBridges
favicon: null
layout_spectrum: 0
typography_spectrum: 0.79958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbe8'
    - '#e1b55e'
    - '#191012'
    - '#a2613c'
    - '#5f251b'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
