name: BrandonBridges
favicon: null
layout_spectrum: 0.26793
typography_spectrum: 0.79958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9b7ba'
    - '#9b856d'
    - '#f0e3d2'
    - '#684a2e'
    - '#1f160d'
  brandStrength: 0.9634727577213198
  lightness: 0.611124699935317
  saturation: 0.1875
  rhythmicContrast: 0.5750466147437692
purpose: []
